[package]
name = "wick"
version = "0.0.1-1.1.0"
authors = ["Christos Katsakioris <ckatsak@gmail.com>"]
edition = "2021"
rust-version = "1.62"
description = "An unofficial client crate for Firecracker, somewhat based on the OpenAPI-generated client."
readme = "README.md"
repository = "https://github.com/ckatsak/wick-rs/"
license = "Apache-2.0"

[dependencies]
hyper = { version = "0.14", default_features = false, features = ["client", "http1"] }
hyperlocal = { version = "^0.8", default_features = false, features = ["client"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = { version = "^0.1.35", features = ["max_level_trace", "release_max_level_error"] }
url = "^2.2"

[dev-dependencies]
